# Generated by Django 3.2.5 on 2021-08-31 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('login_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=9)),
                ('webiste_id', models.CharField(max_length=9)),
                ('ip', models.GenericIPAddressField(unpack_ipv4=True)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('security_status', models.CharField(choices=[('secured', 'Secured'), ('unsecured', 'Unsecured')], default='secured', max_length=10)),
                ('medium', models.CharField(choices=[('web', 'Website'), ('app', 'Application')], default='web', max_length=4)),
            ],
        ),
    ]
