# Generated by Django 3.2.5 on 2021-09-01 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthPanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteowner',
            name='domain',
            field=models.URLField(max_length=64, unique=True, verbose_name='Website'),
        ),
    ]
